"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$directory$git_branch$time$python$jobs
$character
"""

[username]
show_always = true

[time]
disabled = false
time_format = "%H:%M"
format = "at [$time]($style) "
style = "bold green"
